services:
  cpp-env:
    build: .
    container_name: cpp-dev-env
    privileged: true
    volumes:
      - type: bind
        source: ..                 # Host directory of the project
        target: /workspace         # Container's working directory
      - type: bind                 # Make git credentials available in the container
        source: ~/.ssh              
        target: /root/.ssh       
      - type: bind                  # Preserve bash history
        source: ~/.bash_history
        target: /root/.bash_history
      - type: bind                  # Preserve fish history
        source: ~/.local/share/fish/fish_history
        target: /root/.local/share/fish/fish_history 

    ports:
      - "3333:3333"                # OpenOCD port
      - "4444:4444"                # GDB debugging port
    stdin_open: true
    tty: true
    working_dir: /workspace
    command: /usr/bin/fish         # Start with Fish shell
